spring:
  datasource:
    url: jdbc:mariadb://172.30.1.75:3306/io053001imgsvr
    username: webdc
    password: itro
    driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  type-aliases-package: hospital_test.test.mapper
  mapper-locations: mybatis/mapper/**/*.xml
  jpa:
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
       show_sql: true
       format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace